### ISSUE TITLE
Unable to comment using ctrl+/ shotcut for vscode version 1.0.0

### ISSUE THREAD

**Issue by AmirulOm** [Gimly/vscode-fortran#1]
Hi, I unable to use the ctrl+/ shortcut command my FORTRAN (.f90) codes. it return error and as below

`Unexpected exception while executing command.`

Im currently using vscode version 1.0.0, Red Hat Enterprise Linux Workstation release 7.2 (Maipo). Can you reproduce the error at your side? thanks you.

Amirul

**Comment by mpiannucci** [comment]
It says in the read me that .f90 files are interpreted as MATLAB which they are not so I am not sure if maybe that is causing the plugin to not work

**Comment by AmirulOm** [comment]
Any alternative of suggestion?.. it works before though in the old version.. Anyway beside this issue everything works perfectly..

**Comment by Gimly** [comment]
Hi,

I'm sorry but what is the CTRL+/ shortcut supposed to do? I've tried on my machine with a f90 code open and it doesn't crash when I press CTRL+/, but it doesn't do anything either.

This extension doesn't bring any shortcut in VS Code, it only adds the syntaxe for code colorisation and a few snippets.

@mpiannucci thanks for the heads up, the readme was wrong. I wrote the Matlab extension for VS Code too and I had copy-pasted the readme from it and forgot to change this phrase. It's fixed now, but it definitely doesn't have anything to do with the error @mpiannucci sees.

**Comment by Gimly** [comment]
Oh, interesting, I've searched further, and I see that it's linked to the comment/uncomment action. It seems to be the uncomment that triggers the exception. I'm going to check where it's coming from, but it might be a VS Code bug.

I'm checking that and getting back asap.

**Comment by Gimly** [comment]
Finally found what the issue was, it was a mistake in the way I was declaring the single line comment in the configuration. I've published a new version of the extension and it should be working now.

Have fun :)

**Comment by AmirulOm** [comment]
Nice.. Thanks @Gimly ..
