### ISSUE TITLE
Exclamation mark comment support in fixed format mode

### ISSUE THREAD

**Issue by daloic** [Gimly/vscode-fortran#10]
Using Punchcard mode, Intel Fortran and gfortran support the exclamation mark to put inline comments at the end of a line. I was able to enable this functionality by adding the following pattern in `fortran.tmLanguage`:

		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=!-)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.ruby</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>!-</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.fortran</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.exclamation.mark.fortran.modern</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\\s*\n</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>

The pattern is directly taken from `modern.tmLanguage`.

**Comment by Cordusio** [comment]
I would like to try this but cannot locate `fortran.tmLanguage`... Where is it supposed to be? Thanks.

**Comment by Gimly** [comment]
@Cordusio I would be glad to get a bit of help. The `fortran.tmLanguage` is located in the `syntaxes` folder

**Comment by daloic** [comment]
This is not an issue for me anymore. I am closing it. Feel free to reopen if still needed.
